name: "Sign Osctrl Docker images"
description: "Sign Osctrl Docker images"
inputs:
  osctrl_component:
    required: true
    description: Define the osctrl component to compile
  docker_tags:
    required: true
    description: Define the Docker tag
  docker_image_digests:
    required: true
    description: Dockerhub image digest
  docker_hub_org:
    required: true
    description: Pass DockerHub org to action
  docker_hub_username:
    required: true
    description: Pass DockerHub username to action
  docker_hub_access_token:
    required: true
    description: Pass DockerHub access token to action
  codesign_password:
    required: true
    description: Provide password for codesign private key
  codesign_private_key:
    required: true
    description: Provide codesign private key
  codesign_public_cert:
    required: true
    description: Provide codesign private cert

runs:
  using: "composite"
  steps:
    ########################### Checkout code ###########################
    - name: Checkout code
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 2

    ########################### Install cosign ###########################
    # https://github.com/sigstore/cosign-installer
    - name: Install cosign
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v1.8.0'

    ########################### Log into Dockerhub ###########################
    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ inputs.docker_hub_username }}
        password: ${{ inputs.docker_hub_access_token }}

    ########################### Sign built Docker image using cosign ###########################
    - name: Sign the published Docker image
      shell: bash
      env:
        COSIGN_PASSWORD: "${{ inputs.codesign_password }}"
      run: |
        echo "${{ inputs.codesign_private_key }}" > cosign.key
        for tag in ${{ inputs.docker_tags }} 
        do
          IMAGE_NAME="${{ inputs.docker_hub_org }}/osctrl-${{ inputs.osctrl_component }}:$tag"
          for digest in ${{ inputs.docker_image_digest }}
          do
            cosign sign --key cosign.key docker.io/$IMAGE_NAME@$digest
          done
        done
        rm -f cosign.key

    ########################### Verify signed image using cosign ###########################
    - name: Verify the signed published Docker image
      shell: bash
      run: |
        echo "${{ inputs.codesign_public_cert }}" > cosign.key
        for tag in ${{ inputs.docker_tags }} 
        do
          IMAGE_NAME="${{ inputs.docker_hub_org }}/osctrl-${{ inputs.osctrl_component }}:$tag"
          for digest in ${{ inputs.docker_image_digest }}
          do
            cosign verify --key cosign.key docker.io/$IMAGE_NAME@$digest
          done
        done
        rm -f cosign.key
